# Generated by Django 3.2.7 on 2021-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerns',
            name='findings',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='concerns',
            name='person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='concerns',
            name='resolution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='concerns',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
