# Generated by Django 3.2.7 on 2021-09-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerns',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
