# Generated by Django 3.2.7 on 2021-09-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0003_rename_findings_concerns_problems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concerns',
            old_name='problems',
            new_name='problem',
        ),
    ]
