# Generated by Django 3.2.7 on 2021-09-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0005_alter_concerns_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerns',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
