# Generated by Django 3.2.7 on 2021-09-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0007_concerns_additional_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerns',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
    ]
