# Generated by Django 3.2.7 on 2021-10-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0009_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerns',
            name='status',
            field=models.CharField(blank=True, choices=[('DN', 'Done'), ('WA', 'Waiting')], default='DN', max_length=20),
        ),
    ]
